version: "3.8"
services: 
    server_main:
        image: nginx:stable-alpine
        ports:
            - 81:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on: 
            - blogsapi1
    blogsapi1:
        build:
            context: ./dockerfiles
            dockerfile: blogsapi.dockerfile
        volumes:
            - ./:/var/www/blogsapi1  
